spring:
  datasource:
      url: jdbc:mysql://176.148.8.97/dcdb?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: root
mybatis:
   mapperLocations: classpath:/mapper/*.xml
